In [4]:
import sys
sys.path.append('../')

In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [22]:
import numpy as np
import pandas as pd

import tiktoken

from src.config.paths import MOVIE_PATH, FRIENDS_PATH, SUPREME_PATH, IQ2_PATH, WIKI_PATH, TENNIS_PATH, DATA_PATH

# Datasets

## Dataset 1: Movies

In [14]:
df = pd.read_json(MOVIE_PATH.joinpath('utterances.jsonl'), lines=True)

In [15]:
df.sort_values(['conversation_id', 'id'])

,id,conversation_id,text,speaker,meta,reply-to,timestamp,vectors
142617,L100001,L100001,Then why did you go see Mr. Koehler in the fir...,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 4, 'tok...",NaN,NaT,[]
142616,L100002,L100001,Because he called me.,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 2, 'tok...",L100001,NaT,[]
142711,L100003,L100003,"Hi, Joe.",u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 0, 'tok...",NaN,NaT,[]
142710,L100004,L100003,Frank -- what are you doing here?,u4170,"{'movie_id': 'm278', 'parsed': [{'rt': 5, 'tok...",L100003,NaT,[]
142709,L100005,L100003,I need to ask you a question. What made you g...,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 1, 'tok...",L100004,NaT,[]
...,...,...,...,...,...,...,...,...
142618,L100000,L99996,No.,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 0, 'tok...",L99999,NaT,[]
142622,L99996,L99996,I'm gonna go to jail. I know they're gonna ma...,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 2, 'tok...",NaN,NaT,[]
142621,L99997,L99996,Why'd you come here?,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 3, 'tok...",L99996,NaT,[]
142620,L99998,L99996,To show you this. It's a letter from that law...,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 1, 'tok...",L99997,NaT,[]
142619,L99999,L99996,You didn't know about it before that?,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 3, 'tok...",L99998,NaT,[]

In [16]:
len(df['id']) / len(df['conversation_id'].unique())

3.6669554857576085

## Dataset 2: Friends

In [122]:
df = pd.read_json(FRIENDS_PATH.joinpath('utterances.jsonl'), lines=True)

In [124]:
df.sort_values(['conversation_id', 'id'])

,id,conversation_id,text,speaker,meta,reply-to,timestamp,vectors
142617,L100001,L100001,Then why did you go see Mr. Koehler in the fir...,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 4, 'tok...",NaN,NaT,[]
142616,L100002,L100001,Because he called me.,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 2, 'tok...",L100001,NaT,[]
142711,L100003,L100003,"Hi, Joe.",u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 0, 'tok...",NaN,NaT,[]
142710,L100004,L100003,Frank -- what are you doing here?,u4170,"{'movie_id': 'm278', 'parsed': [{'rt': 5, 'tok...",L100003,NaT,[]
142709,L100005,L100003,I need to ask you a question. What made you g...,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 1, 'tok...",L100004,NaT,[]
...,...,...,...,...,...,...,...,...
142618,L100000,L99996,No.,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 0, 'tok...",L99999,NaT,[]
142622,L99996,L99996,I'm gonna go to jail. I know they're gonna ma...,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 2, 'tok...",NaN,NaT,[]
142621,L99997,L99996,Why'd you come here?,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 3, 'tok...",L99996,NaT,[]
142620,L99998,L99996,To show you this. It's a letter from that law...,u4168,"{'movie_id': 'm278', 'parsed': [{'rt': 1, 'tok...",L99997,NaT,[]
142619,L99999,L99996,You didn't know about it before that?,u4166,"{'movie_id': 'm278', 'parsed': [{'rt': 3, 'tok...",L99998,NaT,[]

In [125]:
len(df) / len(df['conversation_id'].unique())

3.6669554857576085

## Dataset 3: Supreme Court Hearings

In [127]:
df = pd.read_json(SUPREME_PATH.joinpath('utterances.jsonl'), lines=True)

In [128]:
df.sort_values(['conversation_id', 'id'])

,id,conversation_id,text,meta,reply_to,speaker
3181,12990__0_000,12990,"Number 48, Communist Party of the United State...","{'case_id': '1955_48', 'start_times': [0.0, 12...",NaN,j__earl_warren
3182,12990__0_001,12990,"Thank you, sir.\nMay it please the Court.\nThi...","{'case_id': '1955_48', 'start_times': [14.337,...",12990__0_000,john_j_abt
3183,12990__0_002,12990,Is there in the record a sample registration f...,"{'case_id': '1955_48', 'start_times': [318.817...",12990__0_001,<INAUDIBLE>
3184,12990__0_003,12990,"Not in the record, Your Honor.\nThe Attorney G...","{'case_id': '1955_48', 'start_times': [322.834...",12990__0_002,john_j_abt
3185,12990__0_004,12990,Their -- their provisions for destroying your ...,"{'case_id': '1955_48', 'start_times': [625.75]...",12990__0_003,j__stanley_reed
...,...,...,...,...,...,...
1688676,25053__3_023,25053,"Well, if that's the case, then I think your wh...","{'case_id': '2019_17-1618', 'start_times': [35...",25053__3_022,j__samuel_a_alito_jr
1688677,25053__3_024,25053,Of course it is.\nNo one has claimed that sexu...,"{'case_id': '2019_17-1618', 'start_times': [36...",25053__3_023,pamela_s_karlan
1688678,25053__3_025,25053,"Well, let me amend it. Your argument is that s...","{'case_id': '2019_17-1618', 'start_times': [36...",25053__3_024,j__samuel_a_alito_jr
1688679,25053__3_026,25053,"If there was that case, it might be the rare c...","{'case_id': '2019_17-1618', 'start_times': [36...",25053__3_025,pamela_s_karlan
1688680,25053__3_027,25053,"Thank you, counsel.\nThe case is submitted.","{'case_id': '2019_17-1618', 'start_times': [37...",25053__3_026,j__john_g_roberts_jr

In [129]:
len(df) / len(df['conversation_id'].unique())

217.57566841499298

This is obviously a lot better, but the concern is this isnt really representative of conversational speech and is very biased. Anything trained on it will inherently exploit the much easier underlying latent structure these court hearings entail where there is typically one questioner and one answerer for each snippet.

## Dataset 4: Intelligence Squared

In [7]:
df = pd.read_json(IQ2_PATH.joinpath('utterances.jsonl'), lines=True)

In [135]:
df.sort_values(['root', 'id'])

,id,root,text,user,meta,reply-to,timestamp
0,0,0,… And now I’d like to introduce Robert Rosenkr...,Bob Costas,"{'nontext': {'applause': [[0, 29]]}, 'segment'...",NaN,NaT
1,1,0,"Well thank you very much. And, uh, uh, on beha...",Robert Rosenkranz,"{'nontext': {'applause': [[0, 445]]}, 'segment...",0.0,NaT
2,2,0,"Thank you again, Bob. So this is the sixth deb...",Bob Costas,"{'nontext': {'pause': [[0, 237]], 'applause': ...",1.0,NaT
3,3,0,Thank you. Everyone in this room uses performa...,Norman Fost,"{'nontext': {'audiencelaughter': [[0, 500], [0...",2.0,NaT
4,4,0,"That is deep-, deeply, deeply Freudian.",Bob Costas,"{'nontext': {'audiencelaughter': [[0, 6]]}, 's...",3.0,NaT
...,...,...,...,...,...,...,...
26557,26557,26330,"Thank you, Arianna Huffington. Our motion is “...",John Donvan,"{'nontext': {}, 'segment': 2, 'paragraphbreaks...",26556.0,NaT
26558,26558,26330,"Ninety-nine years ago, a guy stood up at a pol...",Zev Chafets,"{'nontext': {}, 'segment': 2, 'paragraphbreaks...",26557.0,NaT
26559,26559,26330,"Thank you, Zev Chafets. Our motion, “The two-p...",John Donvan,"{'nontext': {}, 'segment': 2, 'paragraphbreaks...",26558.0,NaT
26560,26560,26330,"Many of you have been looking at our side, at ...",David Brooks,"{'nontext': {'laughter': [[0, 20], [0, 37]], '...",26559.0,NaT
26561,26561,26330,David Brooks. And that completes our closing s...,John Donvan,"{'nontext': {'applause': [[2, 30], [3, 44], [5...",26560.0,NaT

In [ ]:
len(df) / len(df['root'].unique())

245.94444444444446

## Dataset 5: Wiki Talk Page Conversations

In [10]:
df = pd.read_json(WIKI_PATH.joinpath('utterances.jsonl'), lines=True)

In [11]:
df.sort_values(['root', 'id'])

,id,root,text,user,meta,reply-to,timestamp
2,1,1,"Yes, that's good. Revathy's page looked very r...",Johannes003,{'is-admin': False},NaN,1.310744e+09
3,2,1,"Nagma'a site, at least that filmography page, ...",Johannes003,{'is-admin': False},1.0,1.310746e+09
4,3,1,I don't think there are many such official rel...,Johannes003,{'is-admin': False},2.0,1.310751e+09
5,4,1,"Most of the so called \""official sites\"" are m...",Michael-Billa,{'is-admin': False},NaN,1.311762e+09
12,6,6,"Hey, who said so? Frankly, I have absolutely n...",Johannes003,{'is-admin': False},NaN,1.312057e+09
...,...,...,...,...,...,...,...
167837,618498,618496,"Well, unfortunately, if you continue to insist...",Cumulus Clouds,{'is-admin': False},NaN,1.192778e+09
132422,618502,618502,I had the article undeleted - it had been spee...,Royalbroil,{'is-admin': False},NaN,1.194212e+09
132423,618503,618502,I don't know if you are up to date on [[USAR H...,Royalbroil,{'is-admin': False},618502.0,1.194265e+09
74642,618505,618505,Just a short message to let you know that ther...,Royalbroil,{'is-admin': True},NaN,1.197368e+09
74643,618506,618505,I nominated [[Chase Austin]] for DYK. I undele...,Royalbroil,{'is-admin': True},618505.0,1.197522e+09

In [12]:
len(df) / len(df['root'].unique())

3.1230565399227403

## Dataset 6: Tennis Post-Match Press Conferences

In [17]:
df = pd.read_json(TENNIS_PATH.joinpath('utterances.jsonl'), lines=True)

In [18]:
df.sort_values(['root', 'id'])

,id,root,text,user,meta,reply-to,timestamp
94491,0_0.a,0_0.q,"Yeah, I served extremely well, and then the tw...",Andy Murray,"{'is_answer': True, 'is_question': False, 'pai...",0_0.q,2015-06-21
94490,0_0.q,0_0.q,That last set seemed like a faultless performa...,REPORTER,"{'is_answer': False, 'is_question': True, 'pai...",NaN,2015-06-21
94493,0_1.a,0_1.q,"No, I don't think so. You know, it was an unfo...",Andy Murray,"{'is_answer': True, 'is_question': False, 'pai...",0_1.q,2015-06-21
94492,0_1.q,0_1.q,"Did playing the semifinal, finishing that off ...",REPORTER,"{'is_answer': False, 'is_question': True, 'pai...",NaN,2015-06-21
94511,0_10.a,0_10.q,"Well, he was obviously a great player. I think...",Andy Murray,"{'is_answer': True, 'is_question': False, 'pai...",0_10.q,2015-06-21
...,...,...,...,...,...,...,...
83048,9_2.q,9_2.q,What will you be doing between now and Wimbledon?,REPORTER,"{'is_answer': False, 'is_question': True, 'pai...",NaN,2015-06-18
83051,9_3.a,9_3.q,"As I said, it's never easy. It's first week on...",Grigor Dimitrov,"{'is_answer': True, 'is_question': False, 'pai...",9_3.q,2015-06-18
83050,9_3.q,9_3.q,A lot of the big guys struggled here. How do y...,REPORTER,"{'is_answer': False, 'is_question': True, 'pai...",NaN,2015-06-18
83053,9_4.a,9_4.q,I don't want to say more disappointed. It's ju...,Grigor Dimitrov,"{'is_answer': True, 'is_question': False, 'pai...",9_4.q,2015-06-18
83052,9_4.q,9_4.q,How would you compare your loss today with the...,REPORTER,"{'is_answer': False, 'is_question': True, 'pai...",NaN,2015-06-18

In [19]:
len(df) / len(df['root'].unique())

2.0

This has like separate subroots for each question that are still being treated as different roots, a little unclean but good potential

# Tiktoken Testing

In [ ]:
tiktoken.list_encoding_names()

['gpt2',
 'r50k_base',
 'p50k_base',
 'p50k_edit',
 'cl100k_base',
 'o200k_base',
 'o200k_harmony']

In [ ]:
enc = tiktoken.get_encoding('cl100k_base')

In [ ]:
enc._special_tokens

{'<|endoftext|>': 100257,
 '<|fim_prefix|>': 100258,
 '<|fim_middle|>': 100259,
 '<|fim_suffix|>': 100260,
 '<|endofprompt|>': 100276}

In [ ]:
tokens = enc.token_byte_values()

In [ ]:
tokens

[b'\x00',
 b'\x01',
 b'\x02',
 b'\x03',
 b'\x04',
 b'\x05',
 b'\x06',
 b'\x07',
 b'\x08',
 b'\t',
 b'\t\t',
 b'\t\t\t',
 b'\t\t\t\t',
 b'\t\t\t\t\t',
 b'\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
 b'\t\t\t\t\t\t\t\t\t\t\t\n',
 b'\t\t\t\t\t\t\t\t\t\t\n',
 b'\t\t\t\t\t\t\t\t\t\t ',
 b'\t\t\t\t\t\t\t\t\t\n',
 b'\t\t\t\t\t\t\t\t\t ',
 b'\t\t\t\t\t\t\t\t\t  ',
 b'\t\t\t\t\t\t\t\t\n',
 b'\t\t\t\t\t\t\t\t\r\n',
 b'\t\t\t\t\t\t\t\t ',
 b'\t\t\t\t\t\t\t\t  ',
 b'\t\t\t\t\t\t\t\n',
 b'\t\t\t\t\t\t\t\r\n',
 b'\t\t\t\t\t\t\t ',
 b'\t\t\t\t\t\t\t  ',
 b'\t\t\t\t\t\t\t   ',
 b'\t\t\t\t\t\t\n',
 b'\t\t\t\t\t\t\r\n',
 b'\t\t\t\t\t\t ',
 b'\t\t\t\t\t\t  ',
 b'\t\t\t\t\t\t   ',
 b'\t\t\t\t\t\t    ',
 b'\t\t\t\t\t\n',
 b'\t\t\t\t\t\n\t\t\t\t\t\n',
 b'\t\t\t\t\t\r\n',
 b'\t\t\t\t\t ',
 b'\t\t\t\t\t  ',
 b'\t\t\t\t\t   ',
 b'\t\t\t\t\t    ',
 b'\t\t\t\t\t     ',
 b'\t\t\t\t\t      ',
 b'\t\t\t\t\t       ',
 b'\t\t\t\t\n',
 b'\t\t\t\t\n\t\t\t\t\n',
 b'\t\t\t\t\r\n',
 b'\t\t\t\t ',
 b'\t\t\t\t  ',
 b'\t\t\t\t   ',
 b'\t\t\t\t    ',
 b'\t\t\t\t     ',
 b'\t\t\t\t      ',
 b'\t\t\t\t       ',
 b'\t\t\t\t           ',
 b'\t\t\t\n',
 b'\t\t\t\n\t\t\t\n',
 b'\t\t\t\n\n',
 b'\t\t\t\r\n',
 b'\t\t\t\r\n\t\t\t\r\n',
 b'\t\t\t ',
 b'\t\t\t \n',
 b'\t\t\t  ',
 b'\t\t\t   ',
 b'\t\t\t    ',
 b'\t\t\t    \t',
 b'\t\t\t     ',
 b'\t\t\t      ',
 b'\t\t\t       ',
 b'\t\t\t        ',
 b'\t\t\t           ',
 b'\t\t\t               ',
 b'\t\t\n',
 b'\t\t\n\t\t\n',
 b'\t\t\n\t\t\n\t\t\n',
 b'\t\t\n\t\n',
 b'\t\t\n\n',
 b'\t\t\r\n',
 b'\t\t\r\n\t\t\r\n',
 b'\t\t\r\n\r\n',
 b'\t\t ',
 b'\t\t \t',
 b'\t\t \n',
 b'\t\t  ',
 b'\t\t  \n',
 b'\t\t   ',
 b'\t\t    ',
 b'\t\t    \t',
 b'\t\t    \t\t',
 b'\t\t    \n',
 b'\t\t     ',
 b'\t\t      ',
 b'\t\t       ',
 b'\t\t        ',
 b'\t\t         ',
 b'\t\t           ',
 b'\t\t            ',
 b'\t\t               ',
 b'\t\t                   ',
 b'\t\t                       ',
 b'\t\n',
 b'\t\n\t\t\n',
 b'\t\n\t\n',
 b'\t\n\t\n\t\n',
 b'\t\n\t\n\t\n\t\n',
 b'\t\n\t\n\n',
 b'\t\n\n',
 b'\t\n\n\n',
 b'\t\r\n',
 b'\t\r\n\t\r\n',
 b'\t\r\n\r\n',
 b'\t ',
 b'\t \t',
 b'\t \t\t',
 b'\t \n',
 b'\t \r\n',
 b'\t  ',
 b'\t  \t',
 b'\t  \n',
 b'\t   ',
 b'\t   \n',
 b'\t    ',
 b'\t    \t',
 b'\t    \t\t',
 b'\t    \t\t\t',
 b'\t    \n',
 b'\t     ',
 b'\t      ',
 b'\t       ',
 b'\t        ',
 b'\t        \t',
 b'\t        \n',
 b'\t         ',
 b'\t          ',
 b'\t           ',
 b'\t            ',
 b'\t             ',
 b'\t              ',
 b'\t               ',
 b'\t                ',
 b'\t                 ',
 b'\t                   ',
 b'\t                       ',
 b'\t                           ',
 b'\tA',
 b'\tADD',
 b'\tAL',
 b'\tAM',
 b'\tAND',
 b'\tASSERT',
 b'\tAT',
 b'\tAction',
 b'\tAdd',
 b'\tAddress',
 b'\tApp',
 b'\tApplication',
 b'\tArray',
 b'\tArrayList',
 b'\tAssert',
 b'\tB',
 b'\tBIT',
 b'\tBOOL',
 b'\tBOOST',
 b'\tBYTE',
 b'\tBase',
 b'\tBlock',
 b'\tBoolean',
 b'\tBuffer',
 b'\tBufferedReader',
 b'\tButton',
 b'\tC',
 b'\tCC',
 b'\tCG',
 b'\tCHECK',
 b'\tCString',
 b'\tCamera',
 b'\tCheck',
 b'\tClass',
 b'\tClient',
 b'\tClose',
 b'\tCode',
 b'\tCollection',
 b'\tColor',
 b'\tCommand',
 b'\tCommon',
 b'\tCon',
 b'\tConfig',
 b'\tConnection',
 b'\tConsole',
 b'\tContext',
 b'\tCopyright',
 b'\tCreate',
 b'\tCreated',
 b'\tD',
 b'\tDB',
 b'\tDBG',
 b'\tDD',
 b'\tDEBUG',
 b'\tDECLARE',
 b'\tDWORD',
 b'\tData',
 b'\tDate',
 b'\tDebug',
 b'\tDefault',
 b'\tDelete',
 b'\tDescription',
 b'\tDestroy',
 b'\tDictionary',
 b'\tDim',
 b'\tDocument',
 b'\tDouble',
 b'\tDraw',
 b'\tDuel',
 b'\tE',
 b'\tEIF',
 b'\tERR',
 b'\tERROR',
 b'\tEXPECT',
 b'\tEditor',
 b'\tElement',
 b'\tEnd',
 b'\tEntity',
 b'\tError',
 b'\tEvent',
 b'\tExpect',
 b'\tExt',
 b'\tF',
 b'\tFILE',
 b'\tFOR',
 b'\tFROM',
 b'\tField',
 b'\tFile',
 b'\tFunction',
 b'\tG',
 b'\tGL',
 b'\tGLuint',
 b'\tGPIO',
 b'\tGUI',
 b'\tGame',
 b'\tGameObject',
 b'\tGet',
 b'\tGlobal',
 b'\tGrid',
 b'\tGtk',
 b'\tH',
 b'\tHAL',
 b'\tHANDLE',
 b'\tHRESULT',
 b'\tHX',
 b'\tHashMap',
 b'\tHttp',
 b'\tI',
 b'\tID',
 b'\tIL',
 b'\tIN',
 b'\tINNER',
 b'\tINT',
 b'\tId',
 b'\tIf',
 b'\tIl',
 b'\tImGui',
 b'\tImage',
 b'\tIn',
 b'\tInit',
 b'\tInitialize',
 b'\tInput',
 b'\tInputStream',
 b'\tInt',
 b'\tInteger',
 b'\tIntent',
 b'\tIt',
 b'\tItem',
 b'\tIterator',
 b'\tJ',
 b'\tJButton',
 b'\tJLabel',
 b'\tJOptionPane',
 b'\tJPanel',
 b'\tJSONObject',
 b'\tJson',
 b'\tK',
 b'\tKEY',
 b'\tKey',
 b'\tL',
 b'\tLCD',
 b'\tLEFT',
 b'\tLL',
 b'\tLOG',
 b'\tLOGGER',
 b'\tLP',
 b'\tLabel',
 b'\tList',
 b'\tLocal',
 b'\tLog',
 b'\tLogger',
 b'\tLong',
 b'\tM',
 b'\tMD',
 b'\tMPI',
 b'\tMain',
 b'\tMap',
 b'\tMat',
 b'\tMatrix',
 b'\tMe',
 b'\tMessage',
 b'\tMessageBox',
 b'\tMethod',
 b'\tModel',
 b'\tMono',
 b'\tMy',
 b'\tN',
 b'\tNS',
 b'\tNSString',
 b'\tNULL',
 b'\tName',
 b'\tNamespace',
 b'\tNdrFc',
 b'\tNdrFcShort',
 b'\tNode',
 b'\tNone',
 b'\tNull',
 b'\tNullCheck',
 b'\tO',
 b'\tON',
 b'\tORDER',
 b'\tObject',
 b'\tOn',
 b'\tOptional',
 b'\tOutput',
 b'\tP',
 b'\tPORT',
 b'\tPage',
 b'\tPath',
 b'\tPlayer',
 b'\tPoint',
 b'\tPort',
 b'\tPreparedStatement',
 b'\tPrint',
 b'\tPublic',
 b'\tPy',
 b'\tQ',
 b'\tQString',
 b'\tQuery',
 b'\tR',
 b'\tRE',
 b'\tREG',
 b'\tREQUIRE',
 b'\tRETURN',
 b'\tROM',
 b'\tRT',
 b'\tRTCK',
 b'\tRTCT',
 b'\tRTDBG',
 b'\tRTE',
 b'\tRTHOOK',
 b'\tRTLI',
 b'\tRTLR',
 b'\tRTLU',
 b'\tRandom',
 b'\tRead',
 b'\tRect',
 b'\tRegister',
 b'\tRender',
 b'\tRequest',
 b'\tResource',
 b'\tResponse',
 b'\tResult',
 b'\tResultSet',
 b'\tReturn',
 b'\tReturns',
 b'\tRoute',
 b'\tRun',
 b'\tRuntime',
 b'\tRuntimeObject',
 b'\tS',
 b'\tSC',
 b'\tSDL',
 b'\tSELECT',
 b'\tSET',
 b'\tSP',
 b'\tST',
 b'\tScanner',
 b'\tSchema',
 b'\tSend',
 b'\tSerial',
 b'\tServer',
 b'\tService',
 b'\tSession',
 b'\tSet',
 b'\tSimple',
 b'\tSize',
 b'\tSo',
 b'\tSpring',
 b'\tStart',
 b'\tState',
 b'\tStatus',
 b'\tString',
 b'\tStringBuffer',
 b'\tStringBuilder',
 b'\tSystem',
 b'\tT',
 b'\tTArray',
 b'\tTEST',
 b'\tTR',
 b'\tTRACE',
 b'\tTask',
 b'\tTest',
 b'\tText',
 b'\tTexture',
 b'\tThe',
 b'\tThis',
 b'\tThread',
 b'\tTime',
 b'\tTitle',
 b'\tToast',
 b'\tToken',
 b'\tTokenName',
 b'\tTokenNameIdentifier',
 b'\tTransform',
 b'\tType',
 b'\tU',
 b'\tUFUNCTION',
 b'\tUI',
 b'\tUINT',
 b'\tUInt',
 b'\tULONG',
 b'\tUN',
 b'\tUObject',
 b'\tUP',
 b'\tUPROPERTY',
 b'\tURL',
 b'\tUpdate',
 b'\tUse',
 b'\tUser',
 b'\tV',
 b'\tValue',
 b'\tVec',
 b'\tVector',
 b'\tVersion',
 b'\tView',
 b'\tVk',
 b'\tW',
 b'\tWHERE',
 b'\tWebElement',
 b'\tWrite',
 b'\tX',
 b'\tY',
 b'\tZ',
 b'\tZEPHIR',
 b'\ta',
 b'\tac',
 b'\taccount',
 b'\tact',
 b'\taction',
 b'\tactive',
 b'\tactor',
 b'\tactual',
 b'\tad',
 b'\tadd',
 b'\taddr',
 b'\taddress',
 b'\tadmin',
 b'\tafx',
 b'\tal',
 b'\talert',
 b'\talign',
 b'\tall',
 b'\talpha',
 b'\tan',
 b'\tand',
 b'\tangle',
 b'\tanim',
 b'\tanimation',
 b'\tans',
 b'\tanswer',
 b'\tap',
 b'\tapi',
 b'\tapp',
 b'\tappend',
 b'\tar',
 b'\tarea',
 b'\targ',
 b'\targs',
 b'\tarr',
 b'\tarray',
 b'\tas',
 b'\tassert',
 b'\tassertEquals',
 b'\tassertFalse',
 b'\tassertNotNull',
 b'\tassertThat',
 b'\tassertTrue',
 b'\tast',
 b'\tasync',
 b'\tat',
 b'\tatomic',
 b'\tattack',
 b'\tattr',
 b'\taudio',
 b'\tauth',
 b'\tauto',
 b'\taux',
 b'\tawait',
 b'\tax',
 b'\tb',
 b'\tback',
 b'\tbackground',
 b'\tbar',
 b'\tbase',
 b'\tbe',
 b'\tbefore',
 b'\tbegin',
 b'\tbest',
 b'\tbg',
 b'\tbit',
 b'\tbl',
 b'\tblock',
 b'\tboard',
 b'\tbody',
 b'\tbool',
 b'\tboolean',
 b'\tboost',
 b'\tborder',
 b'\tbox',
 b'\tbr',
 b'\tbreak',
 b'\tbs',
 b'\tbt',
 b'\tbtn',
 b'\tbuf',
 b'\tbuff',
 b'\tbuffer',
 b'\tbuild',
 b'\tbuilder',
 b'\tbus',
 b'\tbutton',
 b'\tbuttons',
 b'\tbyte',
 b'\tbytes',
 b'\tc',
 b'\tcache',
 b'\tcal',
 b'\tcall',
 b'\tcallback',
 b'\tcamera',
 b'\tcan',
 b'\tcancel',
 b'\tcanvas',
 b'\tcard',
 b'\tcase',
 b'\tcat',
 b'\tcatch',
 b'\tcategory',
 b'\tcb',
 b'\tcc',
 b'\tcd',
 b'\tcell',
 b'\tcenter',
 b'\tcerr',
 b'\tcf',
 b'\tcfg',
 b'\tch',
 b'\tchange',
 b'\tchannel',
 b'\tchar',
 b'\tcheck',
 b'\tchild',
 b'\tchildren',
 b'\tcin',
 b'\tcl',
 b'\tclass',
 b'\tclassName',
 b'\tclear',
 b'\tcli',
 b'\tclick',
 b'\tclient',
 b'\tclock',
 b'\tclose',
 b'\tcm',
 b'\tcmd',
 b'\tcnt',
 b'\tcode',
 b'\tcol',
 b'\tcolor',
 b'\tcolumn',
 b'\tcom',
 b'\tcommand',
 b'\tcomment',
 b'\tcommon',
 b'\tcomponent',
 b'\tcon',
 b'\tconf',
 b'\tconfig',
 b'\tconn',
 b'\tconnect',
 b'\tconnection',
 b'\tconsole',
 b'\tconst',
 b'\tconstexpr',
 b'\tconstructor',
 b'\tcont',
 b'\tcontainer',
 b'\tcontent',
 b'\tcontentPane',
 b'\tcontext',
 b'\tcontinue',
 b'\tcontrol',
 b'\tcontroller',
 b'\tcopy',
 b'\tcore',
 b'\tcount',
 b'\tcounter',
 b'\tcout',
 b'\tcp',
 b'\tcpu',
 b'\tcr',
 b'\tcreate',
 b'\tcs',
 b'\tct',
 b'\tctrl',
 b'\tctx',
 b'\tcuda',
 b'\tcur',
 b'\tcurl',
 b'\tcurr',
 b'\tcurrent',
 b'\tcursor',
 b'\tcv',
 b'\td',
 b'\tdamage',
 b'\tdata',
 b'\tdataType',
 b'\tdate',
 b'\tday',
 b'\tdb',
 b'\tdc',
 b'\tdd',
 b'\tde',
 b'\tdebug',
 b'\tdef',
 b'\tdefault',
 b'\tdefer',
 b'\tdefine',
 b'\tdel',
 b'\tdelay',
 b'\tdelete',
 b'\tdelta',
 b'\tdes',
 b'\tdesc',
 b'\tdescribe',
 b'\tdescription',
 b'\tdest',
 b'\tdev',
 b'\tdevice',
 b'\tdf',
 b'\tdfs',
 b'\tdialog',
 b'\tdie',
 b'\tdiff',
 b'\tdir',
 b'\tdirection',
 b'\tdis',
 b'\tdispatch',
 b'\tdisplay',
 b'\tdist',
 b'\tdistance',
 b'\tdiv',
 b'\tdo',
 b'\tdoc',
 b'\tdocument',
 b'\tdone',
 b'\tdouble',
 b'\tdp',
 b'\tdraw',
 b'\tdriver',
 b'\tds',
 b'\tdst',
 b'\tdt',
 b'\tdto',
 b'\tduration',
 b'\tdx',
 b'\te',
 b'\techo',
 b'\tedit',
 b'\teditor',
 b'\teffect',
 b'\tel',
 b'\telem',
 b'\telement',
 b'\telif',
 b'\telse',
 b'\telseif',
 b'\telsif',
 b'\tem',
 b'\temail',
 b'\temit',
 b'\ten',
 b'\tend',
 b'\tendif',
 b'\tengine',
 b'\tent',
 b'\tentity',
 b'\tentry',
 b'\tenum',
 b'\tenv',
 b'\tep',
 b'\terr',
 b'\terror',
 b'\terrors',
 b'\tes',
 b'\tesc',
 b'\tev',
 b'\teval',
 b'\tevent',
 b'\tevents',
 b'\tex',
 b'\texcept',
 b'\texec',
 b'\texit',
 b'\texp',
 b'\texpect',
 b'\texpected',
 b'\texplicit',
 b'\texport',
 b'\texports',
 b'\text',
 b'\textern',
 b'\tf',
 b'\tfail',
 b'\tfalse',
 b'\tfclose',
 b'\tfd',
 b'\tff',
 b'\tfflush',
 b'\tfi',
 b'\tfield',
 b'\tfields',
 b'\tfile',
 b'\tfilename',
 b'\tfiles',
 b'\tfill',
 b'\tfilter',
 b'\tfinal',
 b'\tfinally',
 b'\tfind',
 b'\tfire',
 b'\tfirst',
 b'\tflag',
 b'\tflags',
 b'\tflash',
 b'\tflex',
 b'\tfloat',
 b'\tfmt',
 b'\tfn',
 b'\tfont',
 b'\tfor',
 b'\tforeach',
 b'\tform',
 b'\tformat',
 b'\tfound',
 b'\tfp',
 b'\tfprintf',
 b'\tfr',
 b'\tframe',
 b'\tfree',
 b'\tfreopen',
 b'\tfriend',
 b'\tfrom',
 b'\tfs',
 b'\tft',
 b'\tfull',
 b'\tfun',
 b'\tfunc',
 b'\tfunction',
 b'\tfwrite',
 b'\tg',
 b'\tgame',
 b'\tgbc',
 b'\tgen',
 b'\tget',
 b'\tgetline',
 b'\tgit',
 b'\tgl',
 b'\tglBind',
 b'\tglColor',
 b'\tglEnable',
 b'\tglUniform',
 b'\tglVertex',
 b'\tglfw',
 b'\tglm',
 b'\tglobal',
 b'\tglog',
 b'\tglut',
 b'\tgo',
 b'\tgoto',
 b'\tgpio',
 b'\tgr',
 b'\tgraph',
 b'\tgrid',
 b'\tgroup',
 b'\tgtk',
 b'\tgui',
 b'\th',
 b'\thandle',
 b'\thandler',
 b'\thas',
 b'\thash',
 b'\thead',
 b'\theader',
 b'\theaders',
 b'\theight',
 b'\thelp',
 b'\thit',
 b'\tholder',
 b'\thost',
 b'\thr',
 b'\ths',
 b'\thtml',
 b'\thttp',
 b'\ti',
 b'\tiNdEx',
 b'\tiVar',
 b'\ticon',
 b'\tid',
 b'\tidx',
 b'\tif',
 b'\til',
 b'\tim',
 b'\timage',
 b'\timg',
 b'\timport',
 b'\tin',
 b'\tinclude',
 b'\tindex',
 b'\tinfo',
 b'\tinit',
 b'\tinitial',
 b'\tinitialize',
 b'\tinline',
 b'\tinput',
 b'\tinsert',
 b'\tinst',
 b'\tinstance',
 b'\tint',
 b'\tintent',
 b'\tinter',
 b'\tinternal',
 b'\tio',
 b'\tip',
 b'\tis',
 b'\tit',
 b'\titem',
 b'\titems',
 b'\titer',
 b'\tj',
 b'\tjQuery',
 b'\tjava',
 b'\tjob',
 b'\tjs',
 b'\tjson',
 b'\tk',
 b'\tkey',
 b'\tkeys',
 b'\tkfree',
 b'\tl',
 b'\tlabel',
 b'\tlabels',
 b'\tlast',
 b'\tlayer',
 b'\tlayout',
 b'\tlbl',
 b'\tlcd',
 b'\tleft',
 b'\tlen',
 b'\tlength',
 b'\tlet',
 b'\tlevel',
 b'\tlib',
 b'\tlight',
 b'\tline',
 b'\tlines',
 b'\tlink',
 b'\tlist',
 b'\tll',
 b'\tload',
 b'\tloc',
 b'\tlocal',
 b'\tlocation',
 b'\tlock',
 b'\tlog',
 b'\tlogger',
 b'\tlogging',
 b'\tlogin',
 b'\tlogrus',
 b'\tlong',
 b'\tloop',
 b'\tlp',
 b'\tlua',
 b'\tm',
 b'\tmain',
 b'\tmake',
 b'\tmanager',
 b'\tmap',
 b'\tmargin',
 b'\tmask',
 b'\tmat',
 b'\tmatch',
 b'\tmatrix',
 b'\tmax',
 b'\tmc',
 b'\tmd',
 b'\tme',
 b'\tmem',
 b'\tmemcpy',
 b'\tmemset',
 b'\tmenu',
 b'\tmesh',
 b'\tmessage',
 b'\tmeta',
 b'\tmethod',
 b'\tmin',
 b'\tmkdir',
 b'\tmock',
 b'\tmod',
 b'\tmode',
 b'\tmodel',
 b'\tmodule',
 b'\tmouse',
 b'\tmov',
 b'\tmove',
 b'\tmp',
 b'\tms',
 b'\tmsg',
 b'\tmutex',
 b'\tmv',
 b'\tmy',
 b'\tmysql',
 b'\tmysqli',
 b'\tn',
 b'\tname',
 b'\tnames',
 b'\tnamespace',
 b'\tnet',
 b'\tnew',
 b'\tnext',
 b'\tnil',
 b'\tno',
 b'\tnode',
 b'\tnodes',
 b'\tnot',
 b'\tnow',
 b'\tns',
 b'\tnull',
 b'\tnum',
 b'\tnumber',
 b'\to',
 b'\tob',
 b'\tobj',
 b'\tobject',
 b'\tof',
 b'\toffset',
 b'\tok',
 b'\told',
 b'\ton',
 b'\tonChange',
 b'\tonClick',
 b'\top',
 b'\topen',
 b'\toperator',
 b'\topt',
 b'\toption',
 b'\toptions',
 b'\topts',
 b'\tor',
 b'\torder',
 b'\torg',
 b'\tos',
 b'\tout',
 b'\toutput',
 b'\toverride',
 b'\tp',
 b'\tpacket',
 b'\tpadding',
 b'\tpage',
 ...]